### ISSUE TITLE
DotNS.GetNationInfo raises System.FormatException

### ISSUE THREAD

**Issue by NotAName320** [kolya5544/dotNS#1]
![image](https://user-images.githubusercontent.com/27144780/213885822-05ab19e7-1ab9-4e73-be6c-292b0e4c4531.png)
Looks like something changed with the API and now the headers aren't working.

**Comment by kolya5544** [comment]
Hello and thank you for your report!

There was an issue with this exception when no default user-agent is set. It should be fixed now, please update to 0.4.1.
