### ISSUE TITLE
Pin larger than max long value

### ISSUE THREAD

**Issue by Grovre** [kolya5544/dotNS#3]
Parsing an X-Pin does not work because the pin returned by NS can be larger than the max signed long value. Two possible solutions are refactoring Pin to be a ulong (if the pin still isn't too large, if so then see Int128) and storing the pin as a string instead.

The runtime exception is raised when constructing DotNS with a username, password and useragent where the pin parsing happens

**Comment by kolya5544** [comment]
Hello! Thank you for providing your solution to this issue. I had also fixed csproj referencing files from outside the project directory. This change will be available as dotNS 0.5.1 on NuGet in a few minutes.
